# Generated by Django 3.2.25 on 2024-08-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
